# Generated by Django 4.2.16 on 2026-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_migrate_to_postgresql'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoritefood',
            new_name='recommender_user_id_797f87_idx',
            old_name='recommender_user_food_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritefood',
            new_name='recommender_session_a7f231_idx',
            old_name='recommender_session_food_idx',
        ),
        migrations.RenameIndex(
            model_name='saveddiet',
            new_name='recommender_created_705e3d_idx',
            old_name='recommender_created_idx',
        ),
        migrations.RenameIndex(
            model_name='saveddiet',
            new_name='recommender_user_id_74cc51_idx',
            old_name='recommender_user_period_idx',
        ),
        migrations.RenameIndex(
            model_name='saveddiet',
            new_name='recommender_session_eca133_idx',
            old_name='recommender_session_period_idx',
        ),
        migrations.RenameIndex(
            model_name='waterlog',
            new_name='recommender_user_id_64d4b6_idx',
            old_name='recommender_user_logdate_idx',
        ),
        migrations.RenameIndex(
            model_name='waterlog',
            new_name='recommender_session_41f4c3_idx',
            old_name='recommender_session_logdate_idx',
        ),
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.CharField(default='International', help_text='Cuisine type (e.g., Indian, Chinese, Italian)', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='glycemic_index',
            field=models.FloatField(blank=True, help_text='Glycemic Index (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='veg',
            field=models.BooleanField(default=False, help_text='Is this food vegetarian?'),
        ),
    ]
