# Generated by Django 4.2.30 on 2026-05-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_add_food_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='gi_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
